/**
 * Clipio import parser — supports both formats:
 *  1. Legacy bare array:   [ { id, label, shortcut, content, ... }, ... ]
 *  2. Versioned envelope:  { version: 1, format: "clipio", exportedAt, snippets: [...] }
 *  3. ZIP envelope (v2):   ZIP file containing export.json + media/ blobs
 */

import type { ParsedSnippet, FormatParser } from "./types";
import type { Snippet } from "@/types";
import type { MediaMetadata } from "@/storage/backends/media";
import { unzipSync } from "fflate";
import { isValidImportedSnippet } from "@/lib/snippet-schema";
import { migrateContentFormat } from "@/lib/content-format-migration";
import { MEDIA_LIMITS } from "@/config/constants";

interface ClipioEnvelope {
  version: number;
  format: "clipio";
  exportedAt?: string;
  snippets: Snippet[];
  media?: MediaMetadata[];
}

export interface ClipioZipImportResult {
  snippets: ParsedSnippet[];
  /** Restored media blobs keyed by their ID from the export. */
  mediaBlobs: Map<string, { blob: Blob; meta: MediaMetadata }>;
  /** IDs of media entries referenced in snippets but missing from the ZIP. */
  missingMediaIds: string[];
}

/**
 * Validation lives in src/lib/snippet-schema.ts, shared with the storage-level
 * import path. A second, weaker copy here is exactly how the two drifted
 * apart: this one never checked bounds, timestamps, tags, or prototype keys.
 */
const isValidSnippet = isValidImportedSnippet;

function snippetToParsed(raw: Snippet): ParsedSnippet {
  // This function, not the shared validator, is what turns a Clipio record into
  // a snippet: `parse` filters with a boolean predicate and then maps the RAW
  // records, so nothing downstream has normalised them. A 1.x record carrying
  // `contentFormat: "html"` therefore has to be converted right here — the flag
  // is the only record that the body is HTML, and once it is dropped the body
  // is treated as markdown for good and inserts as visible escaped text.
  //
  // Both Clipio entry points (the JSON file and the v2 ZIP) funnel through
  // here, so one call covers both. spec: specs/content-format-migration.spec.md
  const snippet = migrateContentFormat(raw);
  return {
    suggestedId: snippet.id,
    label: snippet.label,
    shortcut: snippet.shortcut,
    content: snippet.content,
    tags: snippet.tags ?? [],
    // Clipio snippets are already in our format — no unsupported placeholders
    unsupportedPlaceholders: [],
  };
}

export const ClipioParser: FormatParser = {
  id: "clipio",
  displayName: "Clipio",
  iconUrl: "/icon/128.png",

  canParse(raw: unknown): boolean {
    if (raw === null || typeof raw !== "object") return false;

    // Versioned envelope
    if (
      !Array.isArray(raw) &&
      (raw as Record<string, unknown>)["format"] === "clipio"
    ) {
      return true;
    }

    // Legacy bare array
    if (Array.isArray(raw)) {
      if (raw.length === 0) return true;
      return isValidSnippet(raw[0]);
    }

    return false;
  },

  parse(raw: unknown): ParsedSnippet[] {
    let snippets: Snippet[];

    if (Array.isArray(raw)) {
      snippets = (raw as unknown[]).filter(isValidSnippet);
    } else {
      const envelope = raw as ClipioEnvelope;
      snippets = (envelope.snippets ?? []).filter(isValidSnippet);
    }

    return snippets.map(snippetToParsed);
  },
};

// ---------------------------------------------------------------------------
// ZIP Import
// ---------------------------------------------------------------------------

/**
 * Parse a Clipio v2 ZIP file.
 *
 * Extracts `export.json` and all `media/<id>.<ext>` blobs.
 * Returns parsed snippets, restored media blobs, and a list of missing IDs.
 *
 * Throws if the ZIP is unreadable or `export.json` is malformed.
 */
/**
 * Upper bound on the total *inflated* bytes a Clipio ZIP may produce.
 *
 * `unzipSync` inflates the whole archive before any per-entry validation runs,
 * so without a budget a 42-byte ZIP can exhaust memory in the options page.
 * The budget is derived from MEDIA_LIMITS.MAX_TOTAL_SIZE so the archive limit
 * and the store limit cannot drift apart, plus headroom for export.json — a
 * user at the media cap produces media of exactly MAX_TOTAL_SIZE, and the
 * manifest is on top of it. Without the headroom such a user cannot restore
 * their own backup.
 * spec: specs/media-import-hardening.spec.md
 */
/** Headroom for export.json, which is not media and is not quota-bound. */
export const MAX_MANIFEST_INFLATED_BYTES = 8 * 1024 * 1024;

export const MAX_ZIP_INFLATED_BYTES =
  MEDIA_LIMITS.MAX_TOTAL_SIZE + MAX_MANIFEST_INFLATED_BYTES;

/**
 * Media IDs are produced by crypto.randomUUID() and are interpolated into
 * `{{image:<id>}}` placeholders and used to build the archive path
 * (`media/${id}.`), so an id is only accepted if it is a short, opaque token.
 *
 * The check is deliberately a conservative charset rather than a strict UUID
 * match. A strict match would reject any export whose ids were generated by a
 * different scheme, and a user restoring their own backup is not an attack.
 * What actually matters is that an id cannot contain a path separator, a dot,
 * or the brace/colon characters that would let it escape into a placeholder.
 *
 * spec: specs/media-import-hardening.spec.md
 */
const MEDIA_ID_PATTERN = /^[A-Za-z0-9_-]{1,64}$/;

export function isValidMediaId(id: unknown): boolean {
  return typeof id === "string" && MEDIA_ID_PATTERN.test(id);
}

export async function importClipioZip(
  file: File
): Promise<ClipioZipImportResult> {
  const arrayBuffer = await file.arrayBuffer();

  // fflate's filter callback receives UnzipFileInfo, whose `originalSize` is
  // the inflated size, available BEFORE extraction. That lets us refuse a
  // decompression bomb without first allocating gigabytes.
  let declaredInflated = 0;
  const unzipped = unzipSync(new Uint8Array(arrayBuffer), {
    filter: (info) => {
      declaredInflated += info.originalSize;
      if (declaredInflated > MAX_ZIP_INFLATED_BYTES) {
        throw new Error(
          `Invalid Clipio ZIP: archive inflates to more than ${MAX_ZIP_INFLATED_BYTES} bytes`
        );
      }
      return true;
    },
  });

  const jsonBytes = unzipped["export.json"];
  if (!jsonBytes) {
    throw new Error("Invalid Clipio ZIP: missing export.json");
  }

  const json = new TextDecoder().decode(jsonBytes);
  let envelope: ClipioEnvelope;
  try {
    envelope = JSON.parse(json) as ClipioEnvelope;
  } catch {
    throw new Error("Invalid Clipio ZIP: export.json is not valid JSON");
  }

  if (envelope.format !== "clipio") {
    throw new Error("Invalid Clipio ZIP: export.json is not a Clipio export");
  }

  const snippets = (envelope.snippets ?? []).filter(isValidSnippet);
  const parsedSnippets = snippets.map(snippetToParsed);

  const mediaBlobs = new Map<string, { blob: Blob; meta: MediaMetadata }>();
  const missingMediaIds: string[] = [];

  const mediaMeta = envelope.media ?? [];

  for (const meta of mediaMeta) {
    // Reject ids that are not safe opaque tokens, but report them as missing
    // rather than dropping them silently, so the import wizard can tell the
    // user which media did not come across.
    if (!isValidMediaId(meta.id)) {
      missingMediaIds.push(String(meta.id));
      continue;
    }
    // Look for a matching file in the media/ directory
    const prefix = `media/${meta.id}.`;
    const entry = Object.keys(unzipped).find((k) => k.startsWith(prefix));

    if (entry) {
      const mimeType = meta.mimeType || guessMimeFromPath(entry);
      const blob = new Blob([unzipped[entry].buffer as ArrayBuffer], {
        type: mimeType,
      });
      mediaBlobs.set(meta.id, { blob, meta });
    } else {
      missingMediaIds.push(meta.id);
    }
  }

  return { snippets: parsedSnippets, mediaBlobs, missingMediaIds };
}

function guessMimeFromPath(path: string): string {
  if (path.endsWith(".webp")) return "image/webp";
  if (path.endsWith(".jpg") || path.endsWith(".jpeg")) return "image/jpeg";
  if (path.endsWith(".gif")) return "image/gif";
  return "image/png";
}
